FROM mcr.microsoft.com/mssql/server:2022-latest

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD="StrongPassword123!"
USER root

RUN mkdir -p /usr/src/sql

COPY ./*.sql /usr/src/sql/

COPY run-init.sh /usr/src/run-init.sh
RUN chmod +x /usr/src/run-init.sh

ENTRYPOINT ["/bin/bash", "/usr/src/run-init.sh"]
